### ISSUE TITLE
[QUESTION] New Func, Stickers, 

### ISSUE THREAD

**Issue by BlackYuzia** [kaganus/weapons#10]
hello, sry If I create so many request.

I have 3 question.
- Do you add Stickers to your plugin?
- Do you have any other ideas (functions) for the plugin?
- Will there be any wonderful Plugins? (Do you think of new plugins?)

I hope you give me answer.
Thanks for Attention.

**Comment by wasyady** [comment]
Can u make pattern settings ?

**Comment by kaganus** [comment]
@BlackYuzia if i have new implementations, you'll see them released here, no need to ask.

@wasyady i dont plan to
