### ISSUE TITLE
1v1(Gloves) bug

### ISSUE THREAD

**Issue by wasyady** [kaganus/weapons#12]
I found a bug.
If I wanna use your mod on a 1v1 multi arena ( https://github.com/splewis/csgo-multi-1v1 ) server, need change weapon to other and back (example: ak to knife).
If you don't change, haven't got "hand modell" and you can't shoot with weapon.

You can check this problem, on my server:
213.181.201.226:29015

After change in every round works perfectly!

Thanks in advance for the solution!

**Comment by kaganus** [comment]
] sm plugins
This command was blocked for public viewing.

lol, nice info

**Comment by wasyady** [comment]
I gave a Z flag for you at now ! :)

**Comment by wasyady** [comment]
An image of the problem:
http://steamcommunity.com/id/wacci/screenshot/834707512951888969

**Comment by wasyady** [comment]
Server again online, and wait for you with Z flag! 💃

**Comment by kaganus** [comment]
i have to see the source code of these plugins:

 "new_gloves_v2.smx" new_gloves_v2.smx
 "Nikooo777" (1.0) by Nikooo777 (dont even know what it does)
 "Player models by flags" (1.2) by boomix

**Comment by wasyady** [comment]
"Nikooo777" (1.0) by Nikooo777" = https://forums.alliedmods.net/showthread.php?t=237004 _Deleted_ now.

"Player models by flags" (1.2) by boomix  = https://forums.alliedmods.net/showthread.php?p=2382746 _It's working perfectly_

"new_gloves_v2.smx" new_gloves_v2.smx = It's a modificated AC_Gloves (Vip core removed) https://github.com/diller110/AC_Gloves 
When I turned off, the problem was resolved. **Thanks for idea, and your help.**

But unfortunately the support of gloves is not as great as yours.
That's why I asked if you would not want to make an own edition of it.

**Comment by kaganus** [comment]
well, im not providing another plugins support here. 
maybe ill create my gloves plugin in the future. make sure to follow my  github

**Comment by wasyady** [comment]
I love you!
Thanks for gloves plugin!

I would like donate for you after my payout.

Do you accept a csgo keys or paypal?

**Comment by kaganus** [comment]
well, paypal left turkey a while ago :)

**Comment by wasyady** [comment]
Sorry I did not know.

CS:GO keys ? :)

**Comment by kaganus** [comment]
probably the easiest way, yeah

**Comment by wasyady** [comment]
Your gloves mod working perfectly with 1v1 mod! 👍 
I sent a friend request while you played on my server, but you rejected.

Can you send tradelink ? 
Can I ask how much keyes did you get so far?

**Comment by kaganus** [comment]
my friend list is full, thats probably it

my trade link is in README.md file

i got 4 keys from 2 people only so far lol

**Comment by wasyady** [comment]
fcking tradeban :/

But I don't forget your help!
