### ISSUE TITLE
Knife skins

### ISSUE THREAD

**Issue by szogi1910** [kaganus/weapons#13]
Hello
When someone has a default scythe and chooses skins, instead of setting his skin for a knife, he gives him random skin with random weapons and blocks the purchase of another weapon.

**Comment by kaganus** [comment]
this doesn't even make sense

**Comment by szogi1910** [comment]
I know there is not, but it happens to me if someone chooses a skins for a basic scythe

**Comment by kaganus** [comment]
what do you mean by basic scythe?

**Comment by szogi1910** [comment]
It's about a default knife for csgo

**Comment by kaganus** [comment]
can you tell me what you press in detail? like this:
1. !knife
2. select Karambit
3. !ws
4. select Karambit
5. turn StatTrak Off

etc.

**Comment by szogi1910** [comment]
!ws

**Comment by kaganus** [comment]
ok i cannot find the problem with this type of detail lol
come back with someone who is fluent in english please

**Comment by szogi1910** [comment]
https://www.youtube.com/watch?v=-w5woPh2VhI&feature=youtu.be

**Comment by wasyady** [comment]
What's in the error log?

csgo/addons/sourcemod/configs/core.cfg
Did you set "FollowCSGOServerGuidelines" in the core.cfg?

**Comment by szogi1910** [comment]
No error 
Did you set "FollowCSGOServerGuidelines" in the core.cfg?

The plugin works fine only see I choose knife and it shows up awp

Set the default knife (csgo) on the server and choose skin

**Comment by wasyady** [comment]
Can you give server adress ?

I would like to try it!

**Comment by szogi1910** [comment]
188.165.21.245:28145 password 1234

**Comment by wasyady** [comment]
[https://steamuserimages-a.akamaihd.net/ugc/848218533975929844/D06AEF09F1047C1F8365EF1734FCAD30C6A5C3F8/](url)

[](https://steamuserimages-a.akamaihd.net/ugc/848218533975928897/88356D012D49FB86303CBA04EE3DC63B9DDED1BC/)

I can use !knife, !ws, !nametag, float too.
**It's working everthing perfectly!**

**Comment by szogi1910** [comment]
Ehh ...
The problem is with a standard knife

**Comment by wasyady** [comment]
Default knife can't paintable!

**Comment by szogi1910** [comment]
Check out the video
Writes !ws
I choose a knife skins
Instead of knife is awp

https://www.youtube.com/watch?v=Dkw4pvwAM-4

**Comment by morpig** [comment]
i think I know what he's talking about, he's trying to change his knife skins, but instead showing the AWP menu. am i right?

**Comment by kaganus** [comment]
fixed in v1.0.9 (https://github.com/kaganus/weapons/releases/tag/v1.0.9)

default knife (your own knife) should be disabled in !ws menu, since you cannot modify it. it was disabled before but a change in weapon listing algorithm, broke this on earlier versions.

**Comment by szogi1910** [comment]
@morpig Exactly
@kaganus Ws already blocks the skin setting for the default daemon
write knife
i choose a knife karambit And gets awp
