### ISSUE TITLE
Knife selection

### ISSUE THREAD

**Issue by szogi1910** [kaganus/weapons#14]
Continued - https://github.com/kaganus/weapons/issues/13

@morpig Exactly
@kaganus Ws already blocks the skin setting for the default knife
write !knife
i choose a knife karambit And gets awp

**Comment by szogi1910** [comment]
https://youtu.be/EYEIlEObSdo

**Comment by kaganus** [comment]
ws wasnt blocking skin settings for default knife because of a bug i mentioned on the previous issue, now that is fixed. as to your problem, i understand it, but dont have it on any of my servers. can you list your plugins here? sm plugins list

**Comment by szogi1910** [comment]
01 "Sound Commands" (1.8.0.5998) by AlliedModders LLC
  02 "Weapons & Knives" (1.0.6) by kgns - wasdzone
  03 "Client Preferences" (1.8.0.5998) by AlliedModders LLC
  04 "Admin Menu" (1.8.0.5998) by AlliedModders LLC
  05 "Basic Info Triggers" (1.8.0.5998) by AlliedModders LLC
  06 "Basic Chat" (1.8.0.5998) by AlliedModders LLC
  07 "Basic Comm Control" (1.8.0.5998) by AlliedModders LLC
  08 "Admin Help" (1.8.0.5998) by AlliedModders LLC
  09 "Player Commands" (1.8.0.5998) by AlliedModders LLC
  10 "Reserved Slots" (1.8.0.5998) by AlliedModders LLC
  11 "Basic Votes" (1.8.0.5998) by AlliedModders LLC
  12 "Weapons & Knives" (1.0.9) by kgns - wasdzone
  13 "Nextmap" (1.8.0.5998) by AlliedModders LLC
  14 "Fun Commands" (1.8.0.5998) by AlliedModders LLC
  15 "Fun Votes" (1.8.0.5998) by AlliedModders LLC
  16 "Basic Commands" (1.8.0.5998) by AlliedModders LLC
  17 "Admin File Reader" (1.8.0.5998) by AlliedModders LLC
  18 "RankMe" (3.0.3.Kento.25) by lok1, Scooby, pracc, Kento, Kxnrl
  19 "[CSGO/CSS] Chat/Scoreboard Tag Menu" (1.3.1) by [W]atch [D]ogs
  20 "Basic Ban Commands" (1.8.0.5998) by AlliedModders LLC
  21 "Anti-Flood" (1.8.0.5998) by AlliedModders LLC
  22 "kento_rangi.smx"

**Comment by kaganus** [comment]
why do you have both 1.0.6 AND 1.0.9 versions of my plugin loaded at the same time?

**Comment by szogi1910** [comment]
Incidentally, I later turned off and forgot to edit the list
The bug was in version 1.0.6 
So the problem can be considered solved

**Comment by kaganus** [comment]
thanks for updating, so the issue is solved
