### ISSUE TITLE
Errors log

### ISSUE THREAD

**Issue by Medium553** [kaganus/weapons#15]
please fix errors
version 1.0.9

> L 08/02/2017 - 00:57:59: SourceMod error session started
> L 08/02/2017 - 00:57:59: Info (map "awp_lego_2_sf") (file "errors_20170802.log")
> L 08/02/2017 - 00:57:59: [SM] Exception reported: Invalid timer handle 16d6084f (error 1)
> L 08/02/2017 - 00:57:59: [SM] Blaming: weapons.smx
> L 08/02/2017 - 00:57:59: [SM] Call stack trace:
> L 08/02/2017 - 00:57:59: [SM]   [0] KillTimer
> L 08/02/2017 - 00:57:59: [SM]   [1] Line 192, weapons/menus.sp::FloatMenuHandler
> L 08/02/2017 - 00:58:08: [SM] Exception reported: Invalid timer handle 16d6084f (error 3)
> L 08/02/2017 - 00:58:08: [SM] Blaming: weapons.smx
> L 08/02/2017 - 00:58:08: [SM] Call stack trace:
> L 08/02/2017 - 00:58:08: [SM]   [0] KillTimer
> L 08/02/2017 - 00:58:08: [SM]   [1] Line 192, weapons/menus.sp::FloatMenuHandler
> L 08/02/2017 - 00:59:02: [SM] Exception reported: Invalid timer handle 16d6084f (error 3)
> L 08/02/2017 - 00:59:02: [SM] Blaming: weapons.smx
> L 08/02/2017 - 00:59:02: [SM] Call stack trace:
> L 08/02/2017 - 00:59:02: [SM]   [0] KillTimer
> L 08/02/2017 - 00:59:02: [SM]   [1] Line 192, weapons/menus.sp::FloatMenuHandler
> L 08/02/2017 - 01:18:22: Error log file session closed.
> L 08/02/2017 - 04:57:11: SourceMod error session started
> L 08/02/2017 - 04:57:11: Info (map "awp_lego_2_sf") (file "errors_20170802.log")
> L 08/02/2017 - 04:57:11: [SM] Exception reported: Invalid timer handle 78a40646 (error 1)
> L 08/02/2017 - 04:57:11: [SM] Blaming: weapons.smx
> L 08/02/2017 - 04:57:11: [SM] Call stack trace:
> L 08/02/2017 - 04:57:11: [SM]   [0] KillTimer
> L 08/02/2017 - 04:57:11: [SM]   [1] Line 210, weapons/menus.sp::FloatMenuHandler
> L 08/02/2017 - 04:57:31: [SM] Exception reported: Invalid timer handle 78a40646 (error 1)
> L 08/02/2017 - 04:57:31: [SM] Blaming: weapons.smx
> L 08/02/2017 - 04:57:31: [SM] Call stack trace:
> L 08/02/2017 - 04:57:31: [SM]   [0] KillTimer
> L 08/02/2017 - 04:57:31: [SM]   [1] Line 210, weapons/menus.sp::FloatMenuHandler
> L 08/02/2017 - 05:11:02: Error log file session closed.

and

> L 07/31/2017 - 08:19:54: [weapons.smx] Update Player failed! near "WHERE": syntax error
> L 07/31/2017 - 08:20:21: [weapons.smx] Update Player failed! near "WHERE": syntax error
> L 07/31/2017 - 08:20:27: [weapons.smx] Update Player failed! near "WHERE": syntax error
> L 07/31/2017 - 08:20:41: [weapons.smx] Update Player failed! near "WHERE": syntax error
> L 07/31/2017 - 08:21:11: [weapons.smx] Update Player failed! near "WHERE": syntax error
> L 07/31/2017 - 08:21:17: [weapons.smx] Update Player failed! near "WHERE": syntax error
> L 07/31/2017 - 08:36:55: [weapons.smx] Update Player failed! near "WHERE": syntax error
> L 07/31/2017 - 08:37:00: [weapons.smx] Update Player failed! near "WHERE": syntax error

**Comment by kaganus** [comment]
first set of errors, you can ignore. its working as intended

for the second set of errors, i need more data. those logs do not tell anything
