### ISSUE TITLE
Error Log | Spectator 

### ISSUE THREAD

**Issue by BlackYuzia** [kaganus/weapons#16]
```
L 08/10/2017 - 07:02:28: [SM] Exception reported: Team index 1 is invalid
L 08/10/2017 - 07:02:28: [SM] Blaming: weapons.smx
L 08/10/2017 - 07:02:28: [SM] Call stack trace:
L 08/10/2017 - 07:02:28: [SM]   [0] PTaH_GetItemInLoadout
L 08/10/2017 - 07:02:28: [SM]   [1] Line 56, weapons/hooks.sp::GiveNamedItem
```
I think, player, go to spectators, with open menu, and press buttom. That will be create a that error.
@kaganus You can add **check** spectatorts (spec / no spec) and check team **T** / **CT** (game: CS:GO)

**Comment by kaganus** [comment]
since this error does not cause any problems other than to print the above exception text on the console, this will get fixed later (when i return from vacation)

**Comment by BlackYuzia** [comment]
Okey, Thanks.

**Comment by BlackYuzia** [comment]
@kaganus close if that solved.

**Comment by kaganus** [comment]
not yet :)
