### ISSUE TITLE
 Blaming: weapons.smx

### ISSUE THREAD

**Issue by szogi1910** [kaganus/weapons#17]
L 08/15/2017 - 14:59:25: [SM] Call stack trace:
L 08/15/2017 - 14:59:25: [SM]   [0] PTaH_GetItemInLoadout
L 08/15/2017 - 14:59:25: [SM]   [1] Line 56, weapons/hooks.sp::GiveNamedItem
L 08/15/2017 - 14:59:25: [SM]   [3] GivePlayerItem
L 08/15/2017 - 14:59:25: [SM]   [4] Line 302, warmup.sp::GiveWeapon
L 08/15/2017 - 14:59:25: [SM]   [5] Line 328, warmup.sp::EventPlayerSpawn

**Comment by kaganus** [comment]
this log says nothing, can't help you
