### ISSUE TITLE
[ISSUE] Frezze

### ISSUE THREAD

**Issue by wasyady** [kaganus/weapons#18]
If I use your weapons paint 1.0.10 hotfix, my 1v1 server random frezze (middle of 10mins and 120 mins), don't crash, just freeze. (I didn't have anything in error log) 
I changed back to franug's last weapon mod, server run more than 10 hours.

Plugins list with other ws:

01 "Admin File Reader" (1.8.0.6024) by AlliedModders LLC
02 "Admin Help" (1.8.0.6024) by AlliedModders LLC
03 "Admin Menu" (1.8.0.6024) by AlliedModders LLC
04 "Advertisements" (2.0.2) by Tsunami
05 "AFK Manager" (2.8) by Liam
06 "Anti-Flood" (1.8.0.6024) by AlliedModders LLC
07 "BanId Fix" (0.4) by SM9();
08 "Basic Chat" (1.8.0.6024) by AlliedModders LLC
09 "Basic Comm Control" (1.8.0.6024) by AlliedModders LLC
10 "Basic Commands" (1.8.0.6024) by AlliedModders LLC
11 "Basic Info Triggers" (1.8.0.6024) by AlliedModders LLC
12 "Basic Votes" (1.8.0.6024) by AlliedModders LLC
13 "CallAdmin" (0.1.5) by Impact, Popoklopsi
14 "CallAdmin: Steam module" (0.1.5) by Impact, Popoklopsi
15 "Client Preferences" (1.8.0.6024) by AlliedModders LLC
16 "CS:GO Admin ESP" (2.1) by Root
17 "SM Franug CSGO Sprays" (1.4.2) by Franc1sco Steam: franug, EMINEM
18 "[CS:GO] Fake Competitive Ranks/Coins" (1.2) by Laam4
19 "SM CS:GO Franug Knives" (3.0.6 private version) by Franc1sco franug
20 "CS:GO GiveNamedItem Hook Franug Edition" (4.0.6 private version) by Franc1sco franug and Neuro Toxin
21 "SM CS:GO Weapon Paints" (6.5 private version) by Franc1sco franug
22 "Fun Commands" (1.8.0.6024) by AlliedModders LLC
23 "Fun Votes" (1.8.0.6024) by AlliedModders LLC
24 "Gloves" (1.0.1) by kgns - wasdzone
25 "[ANY] Ban Disconnected Player" (2.0) by Headline, Original Plugin : mad_hamster
26 "[Multi-1v1] Challenge" (1.1.4) by Headline
27 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
28 "RankMe" (3.0.3.Kento.22) by lok1, Scooby, pracc, Kento
29 "MapChooser" (1.8.0.6024) by AlliedModders LLC
30 "Map configs" (1.3) by Berni
31 "SM Most Active" (2.2) by Franc1sco Steam: franug
32 "CS:GO Multi1v1" (1.1.6) by splewis
33 "[CSGO]Multi 1v1 - Deagle 1 Tap" (1.0) by S4muRaY'
34 "CS:GO Multi1v1: flashbangs addon" (1.1.5) by splewis
35 "CS:GO Multi1v1: headshot round addon" (1.0.0) by Bara
36 "CS:GO Multi1v1: knife round addon" (1.1.5) by splewis
37 "[CSGO]Multi 1v1 - No Scope" (1.0) by S4muRaY'
38 "Nextmap" (1.8.0.6024) by AlliedModders LLC
39 "Map Nominations" (1.8.0.6024) by AlliedModders LLC
40 "Player Commands" (1.8.0.6024) by AlliedModders LLC
41 "Player models by flags" (1.2) by boomix
42 "[CSGO] QuakeSounds Overlays edition" (1.0) by TonyBaretta
43 "RandomCycle" (1.8.0.6024) by AlliedModders LLC
44 "Random Emptymap" (1.0) by Zipcore
45 "Reserved Slots" (1.8.0.6024) by AlliedModders LLC
46 "Rock The Vote" (1.8.0.6024) by AlliedModders LLC
47 "sbp.smx" 
48 "SourceBans++: Admin Config Loader" (1.6.2) by AlliedModders LLC, SourceBans++ Dev Team
49 "SourceBans++: Bans Checker" (1.6.2) by psychonic, Ca$h Munny, SourceBans++ Dev Team
50 "SourceBans++: SourceComms" (1.6.2) by Alex, SourceBans++ Dev Team
51 "SourceBans++: Main Plugin" (1.6.2) by SourceBans Development Team, SourceBans++ Dev Team
52 "SourceBans++: SourceSleuth" (1.6.2) by ecca, SourceBans++ Dev Team
53 "Simple Chat Processor (Redux)" (2.1.0) by Simple Plugins, Mini
54 "SourceMod Anti-Cheat" (0.8.6.0) by SMAC Development Team
55 "SMAC Aimbot Detector" (0.8.6.0) by SMAC Development Team
56 "SMAC AutoTrigger Detector" (0.8.6.0) by SMAC Development Team
57 "SMAC Client Protection" (0.8.6.0) by SMAC Development Team
58 "SMAC Command Monitor" (0.8.6.0) by SMAC Development Team
59 "SMAC EAC Global Banlist" (0.8.6.0) by SMAC Development Team
60 "SMAC ESEA Global Banlist" (0.8.6.0) by SMAC Development Team
61 "SMAC Eye Angle Test" (0.8.6.0) by SMAC Development Team
62 "SMAC Rcon Locker" (0.8.6.0) by SMAC Development Team
63 "SMAC Anti-Speedhack" (0.8.6.0) by SMAC Development Team
64 "SMAC Spinhack Detector" (0.8.6.0) by SMAC Development Team
65 "[CSGO] Advanced Admin" (1.5.8) by PeEzZ
66 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
67 "Sound Commands" (1.8.0.6024) by AlliedModders LLC
68 "SQL Admin Manager" (1.8.0.6024) by AlliedModders LLC
69 "Stealth Revived" (0.6) by SM9();
70 "Rotate server graphic banners" (0.3) by HiTmAnY
71 "[SWGM] Command Listener" (1.1) by Someone
72 "Steam Works Group Manager" (1.7) by Someone
73 "[CSGO/CSS] Chat/Scoreboard Tag Menu" (1.5.0) by [W]atch [D]ogs
74 "csgotokens.com token changer" (1.4.5) by Adi - live4net
75 "tVIP" (1.3) by Totenfluch
76 "Updater" (1.2.2) by GoD-Tony
77 "Web Shortcuts CS:GO version" (2.4) by Franc1sco franug and James "sslice" Gray

Server adress:
roadtosilver.hu:29015
I gave Z flag for you.
If you need ftp, I can give for you.

Thank you in advance for your help!

**Comment by wasyady** [comment]
I think my problem was bots.
I will try nobotenforcer tomorrow, and I will report for you.

**Comment by wasyady** [comment]
No bot enforcer, and newest multi 1v1 plugin didn't resolve my freeze problem!

**Comment by kaganus** [comment]
i am on vacation, and have only mobile thethering internet, so i cant join game servers to see or test. so this will have to wait

but you said 1.0.9, and i released 1.0.10, did you try with 1.0.10?

**Comment by wasyady** [comment]
Sorry, I use 1.0.10, just i was bad. 
I tried lastest SM (1.8 6025), but dosn't resolve my problem.

Freeze after 15 mins in freeze time.

**Comment by wasyady** [comment]
I think 1.0.11 resolved my problem! 👍 
Thank you kaganus!

https://pluginal.com/urun/csgo/eklenti/rankme-fake-rank/
Working with Kento RankMe ?
I can pay with Case Key ?

**Comment by kaganus** [comment]
glad its fixed. was waiting for PTaH release to release a stable version. 

lets talk about the latter, thru steam, and after this saturday when im back home from vacation
