### ISSUE TITLE
[BUG] Drop Knife

### ISSUE THREAD

**Issue by BlackYuzia** [kaganus/weapons#19]
Hello @kaganus 
I have a one bug, after last "great" update from Valve.
Wheen I choose knife (all knife) he change.
But, If I choose knife Bayonet Knife, he drop down. (in floor)
Screen:
When I choose knife, all work:
![2017-08-23_150548](https://user-images.githubusercontent.com/25010528/29615304-14a21818-8816-11e7-91fa-4d613cf5892e.png)
But, If I choose Bayonet knife:
![2017-08-23_150606](https://user-images.githubusercontent.com/25010528/29615315-2074b646-8816-11e7-9706-40dd9fe8b81f.png)
Fix pls. Thanks.

**Comment by kaganus** [comment]
should be fixed with 1.0.11
