### ISSUE TITLE
Blaming: weapons.smx

### ISSUE THREAD

**Issue by RED4911** [kaganus/weapons#20]
L 08/23/2017 - 00:04:12: SourceMod error session started
L 08/23/2017 - 00:04:12: Info (map "awp_lego_2") (file "errors_20170823.log")
L 08/23/2017 - 00:04:12: [SM] Exception reported: Team index 0 is invalid
L 08/23/2017 - 00:04:12: [SM] Blaming: weapons.smx
L 08/23/2017 - 00:04:12: [SM] Call stack trace:
L 08/23/2017 - 00:04:12: [SM]   [0] PTaH_GetItemInLoadout
L 08/23/2017 - 00:04:12: [SM]   [1] Line 56, weapons/hooks.sp::GiveNamedItem
L 08/23/2017 - 00:04:12: [SM]   [3] CS_RespawnPlayer
L 08/23/2017 - 00:04:12: [SM]   [4] Line 2270, C:\Users\sourcemod\scripting\deathmatch2.sp::Respawn
L 08/23/2017 - 00:04:12: [SM] Exception reported: Team index 0 is invalid

**Comment by Shaneajm** [comment]
It looks like it's conflicting with another plugin. Try disabling plugins such as AWP Deathmatch/FFA (ones that modify respawn or major gameplay.)

**Comment by RED4911** [comment]
Deathmatch / FFA

**Comment by kaganus** [comment]
should be fixed with 1.0.11
