### ISSUE TITLE
Constant knife spin bug

### ISSUE THREAD

**Issue by Wh1t3Rose** [kaganus/weapons#25]
Hello. I didn't start experiencing this bug until  I switched from Influx Surf Timer to Nikoo's ckSurf Timer [here](https://github.com/nikooo777/ckSurf)

I think it is only happening to Admins for some reason. But it is super annoying because other nearby players can here it and I can't switch to any other weapons (pistol, AK, etc) 

It'll fix itself for a while after the map changes but after a few map changes it'l happen again. It always happens once you load into the map after the map change and never just randomly like after you die, respawn etc. It has to do with when the plugin reloads after map start.

I'm might switch to fluffy's ckSurf [here](https://github.com/fluffyst/Surftimer/issues/14#issuecomment-334951794) later tonight/tomorrow and see if it happens with it.

**Comment by kaganus** [comment]
since you yourself said, it was working without a problem with Influx timer, it means you did something wrong when you were migrating to Nikoo's ckSurf, as all my surf and bhop servers using that exact timer work without this problem you say.

**Comment by kaganus** [comment]
closing this as there were no feedbacks
