### ISSUE TITLE
Skins don't apply properly

### ISSUE THREAD

**Issue by Frioo** [kaganus/weapons#29]
I have installed your plugin on my remote, private dedicated server alongside PTaH as instructed, but unfortunately the skins won't apply. Knife changer works just fine, though.

**Comment by kaganus** [comment]
https://forums.alliedmods.net/showthread.php?t=298770:
Edit csgo/addons/sourcemod/configs/core.cfg => Change "FollowCSGOServerGuidelines" "yes" to "no"

**Comment by Frioo** [comment]
Thanks for a fast response. I changed the value to 'no' and everything works fine, thank you!
