### ISSUE TITLE
Error Mysql

### ISSUE THREAD

**Issue by deusmaks** [kaganus/weapons#30]
Hello. You can fix this error ?

L 01/09/2018 - 00:00:06: SourceMod error session started
L 01/09/2018 - 00:00:06: Info (map "de_dust2") (file "errors_20180109.log")
L 01/09/2018 - 00:00:06: [SM] Exception reported: Array index out-of-bounds (index 64, limit 55)
L 01/09/2018 - 00:00:06: [SM] Blaming: weapon_restrict.smx

**Comment by kaganus** [comment]
"Blaming: weapon_restrict.smx"
