### ISSUE TITLE
Dont do nothing

### ISSUE THREAD

**Issue by tuffboy30** [kaganus/weapons#31]
hello i can selecte knifes, but  the skins for knifes and guns dont work the skins are always default ,what i could be doing wrong ?

**Comment by wasyady** [comment]
Error log ?
Cvars in csgo\addons\sourcemod\configs\core.cfg ?
	"BlockBadPlugins"	"no"
	"FollowCSGOServerGuidelines"	"no"

**Comment by tuffboy30** [comment]
worked thx
