### ISSUE TITLE
Skins weapons, knife and gloves dont working

### ISSUE THREAD

**Issue by toster234** [kaganus/weapons#36]
If i type !knife and set knife its work but if i try to change skin !ws its not working and can't set gloves
Console log:

> L 03/02/2018 - 20:10:02: Starting Freeze period
L 03/02/2018 - 20:10:02: [SM] Exception reported: Cannot set m_iItemIDLow with "FollowCSGOServerGuidelines" option enabled.
L 03/02/2018 - 20:10:02: [SM] Blaming: gloves.smx
L 03/02/2018 - 20:10:02: [SM] Call stack trace:
L 03/02/2018 - 20:10:02: [SM] [0] SetEntProp
L 03/02/2018 - 20:10:02: [SM] [1] Line 148, gloves.sp::GivePlayerGloves
L 03/02/2018 - 20:10:02: [SM] [2] Line 23, gloves/hooks.sp::Event_PlayerSpawn

**Comment by wasyady** [comment]
Edit csgo/addons/sourcemod/configs/core.cfg => Change "FollowCSGOServerGuidelines" "yes" to "no"

Use this without a GSLT token (LAN server), or use a token service for your servers, or your account will be banned from operating game servers, and a month cooldown from playing the game.
