### ISSUE TITLE
Broken server is database can't connect

### ISSUE THREAD

**Issue by winterzz** [kaganus/weapons#37]
I've noticed if the server loses the connection to the sql, the plugin completely breaks the server and makes it unplayable. People can deal hundreds of damage and not kill the enemy player. Any ideas?

**Comment by kaganus** [comment]
can you try to disabled StatTrak feature and see if it happens again when the connection to DB is lost?

btw, this plugin -as all other DB dependent plugins- will not work correctly if you are gonna have connection problems to your DB. it's best to use SQLite if that is the case
