### ISSUE TITLE
skins not stripped when they no longer have access to plugin

### ISSUE THREAD

**Issue by kaeming** [kaganus/weapons#39]
I'm using this plugin for donators only, with admin overrides.
For example if their VIP expires, they cannot have access to command like !ws !knife etc,
BUT, they still have their skins and knifes that are set when they still have access to the plugin.
Is there anyway for me to strip off all their skins and knifes when they no longer have the flags?

**Comment by kaeming** [comment]
Guess i'll have to manually scrap them myself then lol

**Comment by b3none** [comment]
You could just add a check on map load and then if they do not have VIP access then remove the skins they have set.
