### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by RED4911** [kaganus/weapons#43]
L 05/25/2018 - 00:22:31: SourceMod error session started
L 05/25/2018 - 00:22:31: Info (map "awp_lego_2") (file "errors_20180525.log")
L 05/25/2018 - 00:22:31: Error log file session closed.
L 05/25/2018 - 00:28:14: SourceMod error session started
L 05/25/2018 - 00:28:14: Info (map "awp_lego_2") (file "errors_20180525.log")
L 05/25/2018 - 00:28:14: [SM] Exception reported: Client index 0 is invalid
L 05/25/2018 - 00:28:14: [SM] Blaming: weapons.smx
L 05/25/2018 - 00:28:14: [SM] Call stack trace:
L 05/25/2018 - 00:28:14: [SM]   [0] IsClientInGame
L 05/25/2018 - 00:28:14: [SM]   [1] Line 283, weapons/menus.sp::FloatTimer
L 05/25/2018 - 00:33:15: Error log file session closed.
L 05/25/2018 - 07:30:11: SourceMod error session started
L 05/25/2018 - 07:30:11: Info (map "awp_lego_2") (file "errors_20180525.log")
L 05/25/2018 - 07:30:11: [weapons.smx] Delete Inactive Player Data failed! query: "DELETE FROM weapons WHERE steamid in (SELECT steamid FROM weapons_timestamps WHERE last_seen < 1527222430 - (30 * 86400))" error: "Lost connection to MySQL server during query"
L 05/25/2018 - 07:55:57: [SM] Exception reported: Client index 0 is invalid
L 05/25/2018 - 07:55:57: [SM] Blaming: weapons.smx
L 05/25/2018 - 07:55:57: [SM] Call stack trace:
L 05/25/2018 - 07:55:57: [SM]   [0] IsClientInGame
L 05/25/2018 - 07:55:57: [SM]   [1] Line 90, weapons/menus.sp::WeaponsMenuTimer
L 05/25/2018 - 08:22:54: Error log file session closed.

L 05/24/2018 - 23:58:41: SourceMod error session started
L 05/24/2018 - 23:58:41: Info (map "awp_lego_2") (file "errors_20180524.log")
L 05/24/2018 - 23:58:41: [weapons.smx] Update Player failed! query: "UPDATE weapons SET knife_survival_bowie_float =  WHERE steamid = 'STEAM_1:0:143655163'" error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE steamid = 'STEAM_1:0:143655163'' at line 1"

**Comment by kaganus** [comment]
should be fixed with the new release
