### ISSUE TITLE
MySQL SQL syntax error

### ISSUE THREAD

**Issue by Nerus87** [kaganus/weapons#45]
Hi,
I have errors on weapons plugin, please fix it.

> L 06/29/2018 - 21:28:46: [weapons.smx] Update Player failed! query: "UPDATE weapons SET knife_survival_bowie_float = WHERE steamid = 'STEAM_1:0:XXXXXXXXX'" error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE steamid = 'STEAM_1:0:XXXXXXXXX'' at line 1"

> L 06/29/2018 - 210:23: [weapons.smx] Update Player failed! query: "UPDATE weapons SET knife_survival_bowie_float = WHERE steamid = 'STEAM_1:0:XXXXXXXXX'" error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE steamid = 'STEAM_1:0:XXXXXXXXX'' at line 1"

> L 06/29/2018 - 211:41: [weapons.smx] Update Player failed! query: "UPDATE weapons SET knife_survival_bowie_float = WHERE steamid = 'STEAM_1:0:XXXXXXXXX'" error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE steamid = 'STEAM_1:0:XXXXXXXXX'' at line 1"

> L 06/29/2018 - 218:00: Error log file session closed.

**Comment by kaganus** [comment]
should be fixed with the new release
