### ISSUE TITLE
Update skin and fix nametag please

### ISSUE THREAD

**Issue by ThanhByKyTa** [kaganus/weapons#49]
A new Horion

**Comment by ThanhByKyTa** [comment]
Remove or Update color nametag
![image](https://user-images.githubusercontent.com/33537916/43618300-9fca825a-96f1-11e8-9d6b-2b3be3ed2655.png)

**Comment by morpig** [comment]
Don't ask him what to do, do it yourself.

Refer to https://github.com/kaganus/CSGOItemParserForWeaponsPlugin

**Comment by RED4911** [comment]
In the update CS GO added 4 knives
