### ISSUE TITLE
[BUG] Copy & Paste Icons of Knifes

### ISSUE THREAD

**Issue by BlackYuzia** [kaganus/weapons#56]
hi @kaganus 

Found some bug.
When round start. Players get new knife and player(s) get that:
![image](https://user-images.githubusercontent.com/25010528/45086548-0ff15c00-b10c-11e8-99bc-4c7480d14244.png)

>Fix pls. Thanks

**Comment by kaganus** [comment]
not related to this plugin. another plugin is the cause
