### ISSUE TITLE
[Feature Request] Update News Skins & MP5-SD

### ISSUE THREAD

**Issue by paulocrash** [kaganus/weapons#57]
Do you have any plans to update the plugin? Put the new skins and MP5.

@kaganus

**Comment by kleuser75** [comment]
+++
update please @kaganus

**Comment by ThanhByKyTa** [comment]
New skin mp5 
https://csgostash.com/weapon/MP5-SD

**Comment by paulocrash** [comment]
New Knives ...
https://csgostash.com/weapon/Ursus+Knife
https://csgostash.com/weapon/Talon+Knife
https://csgostash.com/weapon/Stiletto+Knife
https://csgostash.com/weapon/Navaja+Knife

New MP5-SD
https://csgostash.com/weapon/MP5-SD

New Horizon Case
https://csgostash.com/case/244/Horizon-Case

2018 Nuke & 2018 Inferno Collection
https://csgostash.com/collection/The+2018+Nuke+Collection
https://csgostash.com/collection/The+2018+Inferno+Collection

@kaganus

**Comment by kaganus** [comment]
Horizon Case skins and new knives are already in the plugin, are you not following the updates?

**Comment by paulocrash** [comment]
@kaganus really sorry...

In case only the others are missing, I believe that NameTag Colors can put again, valve already corrected this, or would it be wrong?

**Comment by kleuser75** [comment]
@kaganus add support MP5-SD in plugin, and new skins 
https://csgostash.com/collection/The+2018+Nuke+Collection
https://csgostash.com/collection/The+2018+Inferno+Collection

**Comment by BlackYuzia** [comment]
@kaganus 
![image](https://user-images.githubusercontent.com/25010528/46530783-8c11c780-c8a3-11e8-9f06-ebff6e5f7852.png)
This new skins have too? (I don't see it)

**Comment by paulocrash** [comment]
> @kaganus
> ![image](https://user-images.githubusercontent.com/25010528/46530783-8c11c780-c8a3-11e8-9f06-ebff6e5f7852.png)
> This new skins have too? (I don't see it)

Nop, these would be the updates we mentioned before, we have to wait for @kaganus

**Comment by distratul** [comment]
https://www110.zippyshare.com/v/3Lk44uW8/file.html
https://www110.zippyshare.com/v/bGs2qQo5/file.html

Plugin and language.cfg for mp5sd skins

**Comment by paulocrash** [comment]
> [https://www110.zippyshare.com/v/3Lk44uW8/file.html ](https://www110.zippyshare.com/v/3Lk44uW8/file.html)
> https://www110.zippyshare.com/v/bGs2qQo5/file.html
> 
> Plugin e language.cfg para skins mp5sd

@kaganus would it be possible to include this update to your plugin and remain with it? He did the Skins Update, Addition of the MP5-SD & MySQL Patch.

I am using and so far no apparent problems...

**Comment by distratul** [comment]
My plugin? Add me on steam: DisTraTuLPe 12 oct. 2018 17:27, Paulo Henrique <notifications@github.com> a scris:
https://www110.zippyshare.com/v/3Lk44uW8/file.html 
https://www110.zippyshare.com/v/bGs2qQo5/file.html
Plugin e language.cfg para skins mp5sd

@kaganus would it be possible to include this update to your plugin and remain with it? He did the Skins Update, Addition of the MP5-SD & MySQL Patch.
I am using and so far no apparent problems...

**Comment by distratul** [comment]
What do you mean by my plugin?

**Comment by kaganus** [comment]
i dont download things from zippyshare, nor should you. you can always contribute to this plugin by forking this repo and sending pull requests for me to review and accept/deny.

if you guys do not know coding and not familiar with databases, i wouldn't use any external modification to this plugin, as they might not be compatible with future updates and cause you to lose your player information.

make sure to check out v1.3.0
