### ISSUE TITLE
Skin pattern change

### ISSUE THREAD

**Issue by Dism0raL** [kaganus/weapons#60]
If you choose any knife and a “wave” skin (any phase), the skin pattern will change in each round.
>[Screenshot first round](https://steamuserimages-a.akamaihd.net/ugc/956348816577396417/C77B9DEA4BC4E8B5E9D09203701C1327BDFADB8C/)<
>[Screenshot second round](https://steamuserimages-a.akamaihd.net/ugc/956348816577393854/DEEDC91A50369438322A73A24FD335B194F62BF6/)<

"Weapons & Knives" (1.3.0) by kgns
PTaH (P Tools and Hooks) (1.0.8): Expanding sdkhooks and sdktools

Thx.

**Comment by BlackYuzia** [comment]
Only me don't see any changes?

**Comment by Dism0raL** [comment]
> Only me don't see any changes?

The pattern has shifted down, to the handle of the knife. For conspicuity, open the pictures in the browser tabs and switch between them.

**Comment by kaganus** [comment]
pattern management will not be added to this plugin anytime soon (maybe never)

**Comment by Dism0raL** [comment]
> pattern management will not be added to this plugin anytime soon (maybe never)


I don't need to control the pattern. It seems you misunderstood me ... Shouldn't a pattern be fixed on knives? As seen on my screenshots, it shifts.

**Comment by kaganus** [comment]
nope, the pattern is generated randomly, because I would have to choose specific patterns for every skin and make them default and non-changable.
