### ISSUE TITLE
Not show weapons

### ISSUE THREAD

**Issue by HLXCommunity** [kaganus/weapons#62]
After update, plugins are working, but not giving any of weapons. I disabled this plugin and works fine. I can get weapon.

Talking about 1v1 Arena mod server.

**Comment by OnlyReFLeX** [comment]
I have the same problem

Public

**Comment by kaganus** [comment]
It's not a problem with this plugin, It's a PTaH issue which is a dependency of this plugin. It is getting updated at the moment though, so hang tight and update your PTaH when it's released.
