### ISSUE TITLE
While choosing "default"

### ISSUE THREAD

**Issue by last2fall** [kaganus/weapons#65]
Hello, I recently came across the glitch with the updated version of this mod, if I choose default skin in !ws it crashes my server(m4a4 tested) if I choose normal skins it works okay, any ideas?

**Comment by last2fall** [comment]
*update* it happens on all weapons (not knifes) just weapons in general whenever i choose "default" server crashes

**Comment by kaganus** [comment]
i cannot replicate this
make sure you;
- downloaded PTaH 1.0.9
- downloaded Weapons&Knives 1.3.2
- removed any other plugin that uses PTaH
- restarted your server
