### ISSUE TITLE
Arena 1v1 Crashing

### ISSUE THREAD

**Issue by morpig** [kaganus/weapons#66]
This commit https://github.com/kaganus/weapons/commit/dc350e76a574cbcebacb903967460a2b03df9875 seems to crash my Arena 1v1 servers, tried recompiling without PTaH_WeaponCanUse seems to work now. 

Maybe add a cvar if it's deathmatch mode? 

note: there's no dump/accelerator/stacktrace available, it just hangs and consuming 100% cpu usage

**Comment by ThanhByKyTa** [comment]
me too

**Comment by kleuser75** [comment]
confirm crash me too in arena 1v1 and some times public

**Comment by kaganus** [comment]
https://github.com/kaganus/weapons/commit/58d36172cede9de4435c2ca22e2b2aaed712fd70 should fix this issue

**Comment by ThanhByKyTa** [comment]
my server still crash

**Comment by kaganus** [comment]
and what makes you think the crash reason is this plugin?

**Comment by ThanhByKyTa** [comment]
Your plugins crash no log lol :(
