### ISSUE TITLE
Duble Knife menu

### ISSUE THREAD

**Issue by kleuser75** [kaganus/weapons#67]
Fix please duble knife menu
![09-12-2018 185909](https://user-images.githubusercontent.com/1523348/49697484-7f368a80-fbea-11e8-8d1b-25850cf5d42f.png)

**Comment by kaganus** [comment]
why did you close this?

**Comment by BlackYuzia** [comment]
Yep. I have the same sometimes

**Comment by kleuser75** [comment]
I fixed this updated translation files and configs

**Comment by BlackYuzia** [comment]
@kleuser75 share with all

**Comment by kleuser75** [comment]
@BlackYuzia чем делится ? обновил файлы перевода и конфиги, у всё норм стало.
