### ISSUE TITLE
[Issue] SQL

### ISSUE THREAD

**Issue by wasyady** [kaganus/weapons#7]
I using your plugin on 3 server with a MySql database.
It's using too many connetion ,and sql server is blocking.

"L 07/02/2017 - 07:15:58: [weapons.smx] Database failure: [1040]: Too many connections"

Can u resole this problem ?

Example, create dump and write only at mapchange ?

**Comment by wasyady** [comment]
Thirdly time this problem. 

L 07/03/2017 - 08:41:45: [sbpp_comms.smx] Connecting to database failed: [1040]: Too many connections

**Comment by wasyady** [comment]
Thirdly time this problem.

L 07/03/2017 - 09:01:29: [weapons.smx] Update Player failed! Can't connect to MySQL server on '213.181.201.xxx' (10061)

**Comment by kaganus** [comment]
should be fixed in v1.0.7

**Comment by wasyady** [comment]
Thanks You for fix!

Your plugin is wonderful!
