### ISSUE TITLE
Info regarding restrictions

### ISSUE THREAD

**Issue by muffik9** [kaganus/weapons#8]
Hello,
Your plugin is great and works fine, so massive big-ups for you.

I ve read on your page on alliedmodders that you are not going to add the option to restrict certain skins or other things to be available only for vips. I am not asking you to do so, but if it is possible, would you be able to point me in the right direction as to how I could do it myself, please ?

Thanks in advance.

**Comment by kaganus** [comment]
if you cant do it yourself, hire a developer with knowledge to do it
