### ISSUE TITLE
[BUG] with AWP [RANDOM SKIN]

### ISSUE THREAD

**Issue by BlackYuzia** [kaganus/weapons#9]
hi, I have one BUG in you weapon-skins-plugin.

If you use: random weapon at weapon: "AWP", anythink not change.
I mean, skins not randomized. Fix this pls.

Thanks. Maybe other weapon have problem with randomized. (MAYBE)

**Comment by kaganus** [comment]
just tried this, it works correctly. could not reproduce. try again and make sure you're doing it correctly

**Comment by BlackYuzia** [comment]
hmm, really. work.
I press "standart" :open_mouth:
